update userenv

diff --git a/.config/zsh/userenv b/.config/zsh/userenv
--- a/.config/zsh/userenv
+++ b/.config/zsh/userenv
@@ -1,21 +1,32 @@
+#shellcheck shell=bash
+
 if [[ -s $HOME/.config/dircolors ]] ; then
-	eval $(dircolors -b $HOME/.config/dircolors) ;
+	eval "$(dircolors -b "$HOME/.config/dircolors")"
 fi
 
-if ! infocmp $TERM &> /dev/null ; then
-	tic $HOME/.config/tmux/terminfo/$TERM.terminfo
+if ! infocmp "$TERM" &> /dev/null ; then
+	termfile="$HOME/.config/tmux/terminfo/$TERM.terminfo"
+	if [[ -s $termfile ]] ; then
+		tic "$termfile"
+	else
+		echo "TERM $TERM is undefined"
+		echo "File $termfile does not exist"
+	fi
 fi
 
-# export EDITOR=code
-# if [[ $(which code) == "code not found" ]] ; then
-export EDITOR=vim
-if [[ $(which vim) == "vim not found" ]] ; then
+if [[ $(which code) != "code not found" ]] ; then
+	export EDITOR=code
+elif [[ $(which hx) != "hx not found" ]] ; then
+	export EDITOR=hx
+elif [[ $(which vim) != "vim not found" ]] ; then
+    export EDITOR=vim
+else
 	export EDITOR=vi
 fi
-# fi
+export VISUAL=$EDITOR
 
-export VISUAL=$EDITOR ;
+if [[ $(which xclip) == "xclip not found" ]] ; then
+	echo "xclip not found"
+fi
 
-if [[ $(which xclip) == "xclip not found" ]] ; then echo "xclip not found" ; fi
-
-REPORTTIME=10 ;
+export REPORTTIME=10 ;
